# Generated by Django 5.1.6 on 2025-02-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Science Fiction', 'Science Fiction'), ('Fantasy', 'Fantasy'), ('Mystery', 'Mystery'), ('Biography', 'Biography'), ('History', 'History'), ('Romance', 'Romance'), ('Horror', 'Horror')], max_length=20)),
                ('is_hardcover', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('pages', models.PositiveIntegerField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('recommendations', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cover_image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('isbn', models.CharField(max_length=13, unique=True)),
            ],
        ),
    ]
